"""Initial migration with tables

Revision ID: ce4c9c6bcfef
Revises: 
Create Date: 2024-08-23 13:33:15.996569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4c9c6bcfef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_hora_criacao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_hora_aquisicao', sa.String(), nullable=False),
    sa.Column('plano_atual_id', sa.String(), nullable=True),
    sa.Column('oferta_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plano_atual_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('ofertas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_hora_criacao', sa.DateTime(), nullable=False),
    sa.Column('plano_id', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moeda', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ofertas_id'), 'ofertas', ['id'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_hora_efetivacao', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('tipo_movimentacao', sa.Enum('ABERTURA', 'ENCERRAMENTO', name='tipomovimentacaoenum'), nullable=False),
    sa.Column('motivo_movimentacao', sa.Enum('NOVO', 'CANCELAMENTO', 'UPGRADE', 'DOWNGRADE', name='motivomovimentacaoenum'), nullable=False),
    sa.Column('plano_id', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moeda', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_ofertas_id'), table_name='ofertas')
    op.drop_table('ofertas')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    # ### end Alembic commands ###
